# Generated by Django 5.2.7 on 2025-11-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_alumno', models.CharField(max_length=20, unique=True)),
                ('nombre_alumno', models.CharField(max_length=100)),
                ('apellido_alumno', models.CharField(max_length=100)),
                ('contra_alumno', models.CharField(max_length=255)),
                ('ciclo_alumno', models.IntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('deuda', models.BooleanField(default=False)),
            ],
        ),
    ]
